# Generated by Django 6.0.2 on 2026-03-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sector', models.CharField(choices=[('BANK', 'Bank'), ('IT', 'IT'), ('FINANCE', 'Finance'), ('HEALTHCARE', 'Healthcare')], max_length=20)),
                ('performance_percent', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pe_ratio', models.FloatField(blank=True, null=True)),
                ('discount_percent', models.FloatField(default=0.0)),
                ('fair_value', models.FloatField(blank=True, null=True)),
                ('discount_level', models.CharField(choices=[('STRONG', 'Strong Opportunity'), ('MODERATE', 'Moderate Opportunity'), ('LOW', 'Low Opportunity')], default='LOW', max_length=10)),
            ],
        ),
    ]
